name-template: '$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
prerelease: true
categories:
  - title: 🚀 New Features and Improvements
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 📝 Documentation
    label: documentation
  - title: 📦 Dependency updates
    labels:
      - dependencies
  - title: 👻 Maintenance
    labels:
      - chore
      - internal
exclude-labels:
  - invalid
  - no-changelog
  - skip-changelog
  - reverted
  - wontfix
template: |
  Thanks to all the contributors of this release 🌈: $CONTRIBUTORS

  # What's Changed
  $CHANGES
replacers:
  - search: '@dependabot-preview'
    replace: '@dependabot'